version: "3.9"
services:
  pakkasenplayground:
    ports:
      - "5000:5000"
    environment:
      TZ: "Europe/Helsinki"
    build:
      context: "."
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    env_file: .env
    entrypoint: ["./docker-compose-entrypoint.sh"]

